# Generated by Django 6.0.5 on 2026-06-03 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_name', models.CharField(max_length=255)),
                ('event_date', models.DateField(default=datetime.datetime.now)),
                ('venue', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
