# Generated by Django 6.0.5 on 2026-06-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('lyrics', models.TextField(blank=True, default='')),
            ],
        ),
    ]
